import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <ul>
          <li>Home</li>
          <li>Contact</li>
          <li>About us</li>
          <li>Blog</li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Coder World
        </h1>

        <p className={styles.description}>
          Where you find solution!
        </p>

        <div className={styles.grid}>
            <div className="blog">
              <h2>Popular Blogs</h2>
              <div className="blogItem">
                <h3>This is the Coder World</h3>
                <p>Lorem ipsum dolor sit amet consectetur.</p>
              </div>
              <div className="blogItem">
                <h3>This is the Coder World</h3>
                <p>Lorem ipsum dolor sit amet consectetur.</p>
              </div>
              <div className="blogItem">
                <h3>This is the Coder World</h3>
                <p>Lorem ipsum dolor sit amet consectetur.</p>
              </div>
              <div className="blogItem">
                <h3>This is the Coder World</h3>
                <p>Lorem ipsum dolor sit amet consectetur.</p>
              </div>
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>This website has been made by Shoaib Jamil</p>
      </footer>
    </div>
  )
}
